---
- name: Install Jenkins on Remote Server
  hosts: jenkins
  become: yes

  tasks:
    - name: Install Java (Jenkins dependency)
      yum:
        name: java-11-openjdk
        state: present

    - name: Add Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started
